site_name: "Base de conocimientos"
site_description: "Documentación organizada por temas"
site_author: "partarrieud"
repo_url: "https://github.com/partarrieud/base-conocimientos"
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/partarrieud/base-conocimientos
